[package]
name = "flyff_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etherparse = "0.11.0"
hex = "0.4.3"
packet = "0.1.4"
pcap = "0.9.2"
